name = "server"
description = "Space Game's server"
version = "0.1.0-dev"

authors = ["Michael Taylor"]
maintainers = ["Michael Taylor <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["server"]

[[depends-on]]
aws = "^25.2.0"

[[depends-on]]
gnatcoll = "^25.0.0"
